# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
domain: github.com/alexpechkarev/places-autocomplete-svelte   
title: Places Autocomplete Svelte
author:
  name: Alexander Pechkarev
  email: "alepechkarev@gmail.com" 
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This Svelte component leverages the Google Maps Places Autocomplete API to provide a user-friendly way to search for and retrieve detailed address information within your SvelteKit applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/alexpechkarev/places-autocomplete-svelte" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  alexpechkarev
show_downloads: true

# Build settings
markdown: kramdown
#theme: minima
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

 

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
